# Header

menu:
  主页: /
  归档: /archives/
  随笔: /tags/随笔/

# SubNav
#subnav:
  #github: http://github.com/
  #weibo: https://weibo.com/
  #rss: "#"
  #zhihu: https://www.zhihu.com/explore
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# rss订阅实现需要插件hexo-generator-feed
rss: /

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# aplayer音乐播放器
# 要支持音乐播放，就必须开启音乐的播放配置和音乐的数据文件。
# 博客 source 目录下的 _data 目录（没有的话就新建一个）中新建 musics.json 文件（存放音乐数据）
# 吸底模式1.9.1之后版本生效。若开启吸底模式，不建议显示标题
music:
  # aplayer 电脑页面
  enable: true # 是否开启
  showTitle: true # 是否显示标题
  title: 听听音乐
  fixed: false # 吸底模式（fixed:true），迷你模式（mini:true），普通模式（注释此行或者设置fixed:false）
  autoplay: false # 是否自动播放
  theme: '#4d4d4d' # 主题色
  loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'list' # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto' # 音频预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  lrcType: 1 # 歌词格式，可选值：3（LRC文件歌词格式），1（JS字符串歌词格式），0（不显示歌词）
  listFolded: true # 列表是否折叠
  listMaxHeight: # 列表最大高度
  # mobile-aplayer 移动端页面
  mobile_enable: true # 是否开启
  mobile_showTitle: true # 是否显示标题
  mobile_title: 
  mobile_fixed: false
  mobile_autoplay: false # 同时开启失效
  mobile_theme: '#4d4d4d'
  mobile_loop: 'all'
  mobile_order: 'list'
  mobile_preload: 'auto'
  mobile_volume: 0.7
  mobile_lrcType: 1
  mobile_listFolded: true
  mobile_listMaxHeight:

# 全局搜索
# 本功能实现需要插件hexo-generator-searchdb所生成的search.xml文件
# 在hexo根目录_config.yml添加如下配置
# search:
#   path: search.xml
#   field: post
# 不开启值为false，开启，值为true
# 使用方法：点击所有文章中的搜索图标
local_search:
  enable: true

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# 字数统计
# 本功能实现需要插件hexo-wordcount
# 不需要使用，直接设置值为false，或注释掉
word_count: true

# 代码块复制
clipboard: true

# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和密码加密后的密文即可.
# 比如
# password: 加密的密文
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: true
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# Miscellaneous
#baidu_analytics: ''
#google_analytics: ''
favicon: /img/avatar.png

#你的头像url
avatar: /img/avatar.png

#是否开启分享
share_jia: true

#评论：1、valine；2、gitalk；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、valine 参考官网：https://valine.js.org
valine:
  enable: true
  appId: lgKQKDBk92WAKzzHw1palka0-MdYXbMMI
  appKey: SIKHT3xm9TdmJ8bQKjtRoReC
  placeholder: '说说你的看法。。。' # 评论框占位提示符
  avatar: 'mp' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10 # 评论列表分页
  visitor: false # 文章访问量统计
  highlight: true # 代码块高亮
  recordIP: false # 是否记录评论者IP

#2、gitalk
gitalk:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:
  admin:

#3、畅言（域名需要备案）
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  #aboutme: '关于我'

friends:
  小贱贱图床: http://pic.xiaojianjian.net/
  聚合图床 - 微博图床: http://tool.mkblog.cn/tuchuang/
  歌曲大全-音乐聚合搜索引擎: http://www.gequdaquan.net/gqss/
  软件安装管家: https://mp.weixin.qq.com/s/zeq1sTmaPsKt7Bsok0Ldrg
  CSS, JavaScript 压缩, 美化, 加密, 解密: https://tool.css-js.com/
  404导航 | 只导航优质资源！: https://no404.icu/
  磁力宝: http://www.clb.biz/
  雨花阁: http://www.yuhuage.biz/
  音乐搜索器 - 多站合一音乐搜索,音乐在线试听: http://music.yujianweb.cn/
  音乐直链搜索工具: https://music.liuzhijin.cn/
  全网音乐免费下载神器: http://www.333ttt.com/up/tool/
  GitHub加速下载工具: http://tool.mkblog.cn/github/
  LeanCloud评论管理: https://akbcd.avosapps.us/
  jsDelivr: https://www.jsdelivr.com/

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家

# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
# backup为备份文件
css:
  main: /main.0cf68a.css
  #main: /backup_main.0cf68a.css
  clipboard: /css/clipboard.css
  #clipboard: /backup/backup_clipboard.css
  aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css #1.10.1
  #aplayer: /css/APlayer.min.css #1.10.1
js:
  mobile: /js/mobile.992cbe.js
  #mobile: /backup/backup_mobile.992cbe.js
  main: /main.0cf68a.js
  #main: /backup/backup_main.0cf68a.js
  slider: /slider.e37972.js
  #slider: /backup/backup_slider.e37972.js
  search: /js/search.js
  #search: /backup/backup_search.js
  script: /js/script.js
  #script: /backup/backup_script.js
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.min.js #3.5.0
  #jquery: /js/jquery-3.4.1.min.js #3.4.1
  scrollProgress: https://cdn.jsdelivr.net/npm/scrollprogress@3.0.2/dist/scrollProgress.min.js #3.0.2
  #scrollProgress: /js/scrollProgress.min.js #3.0.2
  crypto: https://cdn.jsdelivr.net/npm/crypto-js@4.0.0/crypto-js.js #4.0.0
  #crypto: /js/crypto-js.min.js #3.1.9-1
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  #clipboard: /js/scrollProgress.min.js
  aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.9.1/dist/APlayer.min.js #1.9.1
  #aplayer: /js/APlayer.min.js #1.9.1